#!/bin/sh

pkg() {
    package=$1
    if test -z "${package}"; then
        return 0
    fi

    root=/var/vcap/packages
    if test ! -d "${root}/${package}"; then
        echo >&2 "${package}: no such package"
        return 1
    fi

#     for dir in bin sbin; do
#         if test -d "${root}/${package}/${dir}"; then
#                 export PATH="${PATH}:${root}/${package}/${dir}"
#         fi
#     done
    for dir in lib; do
        if test -d "${root}/${package}/${dir}"; then
                if test -z "${LD_LIBRARY_PATH}"; then
                        export LD_LIBRARY_PATH="${root}/${package}/${dir}"
                else
                        export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${root}/${package}/${dir}"
                fi
        fi
    done
    return 0
}

pushd /var/vcap/packages >/dev/null
# for package in boost cgal gdal pcre sfcgal geos gmp jsonc libxml2 mpfr proj; do
for package in pcre geos proj sfcgal gdal; do
        pkg "${package}"
done
popd >/dev/null